version: "2"
services:
  web:
    build:
      context: ./src
    container_name: tomcat_springipt
    volumes:
      - term:/home/term
    links:
      - mysql_springipt:mysql_springipt
    ports: 
      - "9090:8080"
    volumes:
      - ./target/springipt-0.0.1.war:/usr/local/tomcat/webapps/springipt.war
      - ./envar.txt:/usr/local/tomcat/webapps/envar.txt
      - myvol:/home/term
      - ./ssh/id_rsa:/usr/local/tomcat/.ssh/PrivateKey.ppk
      - greyfish:/home/greyfish/users


  mysql_springipt:
    image: mysql
    container_name: mysql_springipt
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=iptweb
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_SERVER
    ports:
      - "6603:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql


volumes:
  data:
    driver: local
  myvol:
    external: true
  greyfish:
    external: true
