version: '2'


services:


    # Main node user orchestration
    conductor:
      build: .
      image: "ipt/conductor"
      container_name: conductor
      ports:
        - "5000:5000"
      environment:
        - REDIS_AUTH
        - orchestra_key
        - URL_BASE
        - PROJECT
      command: go run traffic.go



    influxdb:
      image: "influxdb:latest"
      volumes:
        - ./data/influxdb:/var/lib/influxdb
      ports:
        - "8086:8086"
        - "8083:8083"
      extends:
        file:
          credentials.yml
        service:
          db_creds
      command: "influxd"



    redis:
      image: 'redis:4-alpine'
      environment:
        - REDIS_AUTH
      command: redis-server --requirepass $REDIS_AUTH
      ports:
        - '6379:6379'


    # Starts the automated registry to store local 
    registry:
      image: "registry:2"
      ports:
        - "4000:5000"
      container_name: registry
      restart: always
      environment:
        - REGISTRY_AUTH=simple
