<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<c:set var="contextPath" value="${pageContext.request.contextPath}"/>
<jsp:include page="base.jsp" />


<style>

  .col-container {
    display: table;
    width: 100%;
  }
  .col {
    display: table-cell;
    padding: 0.5%;
  }

  #rcorners_solid {
    border-radius: 0px;
    padding: 2%;
    width: 100%
  }

</style>



<center>
  <div class="col-container" style="width: 95%;">
    <div class="col" style="background: transparent; width: 50%;">
      <h2>What is IPT?</h2>
    </div>

    <div class="col" style="background: transparent; ; width: 50%;">
      <h2>Project News</h2>
    </div>

  </div>
</center>

<br>


<center>
  <div class="col-container" style="width: 95%;">
    <div class="col" style="background:  #f2f3c3; width: 50%;">
      <p>
        Interactive Parallelization Tool (IPT) is a semi-automatic tool that converts a C/C++ serial program into an efficient parallel program by parsing the specification by the users. It is currently being used for teaching parallel programming and supports MPI, OpenMP, and CUDA programming models.
      </p>
      <p>
        You can use IPT from the convenience of your web-browser. It is simple. Start by creating an account on this website or use your existing TACC portal account information.
      </p>
      <p>
        If you login with your TACC portal account credentials, you will be also be able to compile and run the program generated by IPT on two XSEDE systems: Stampede2 and Comet.
      </p>
      <br><br>

      <img src="https://www.tacc.utexas.edu/documents/1084364/1748789/stampede-boinc.jpg/" class="img-responsive" height="90%" width="90%">
    </div>

    <div class="col" style="background: #e5e5e5 ; width: 50%;">
      
    </div>

  </div>
</center>


<jsp:include page="footer.jsp" />
