version: '2'


volumes:
  greyfish:
  influxdb:


services:


  greyfish:
    build: .
    image: "greyfish/standalone"

    ports:
      - "2000-2004:2000-2004"
    volumes:
      - "greyfish:/greyfish"

    environment:
      - greyfish_key
      - greyfish_path
      - greyfish_threads
      - URL_BASE
      - REDIS_AUTH
      - influx_command
      - redis_command

    extends:
      file:
        credentials.yml
      service:
        db_creds

    command: "tail -F anything"


  # Define an InfluxDB service
  influxdb:
    image: influxdb:latest
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    extends:
      file:
        credentials.yml
      service:
        db_creds
    command: "$influx_command"


  redis:
    image: 'redis:4-alpine'
    environment:
      - REDIS_AUTH
    command: "$redis_command"
    ports:
      - '6379:6379'
