version: '3'


volumes:
  greyfish:
  influxdb:


services:

  # Manager node: User orchestration
    manager_node:
        build: ./manager_node
        image: "ipt/manager_node"
        container_name: manager_node
        ports:
            - "5000:5000"
        volumes:
          - greyfish:/greyfish
        environment:
            - REDIS_AUTH
            - orchestra_key
            - URL_BASE
            - PROJECT
            - gthreads
        command: "tail -F anything"


    # Cloud storage
    greyfish:
        build: ./greyfish_storage
        image: "ipt/greyfish"
        container_name: greyfish
        ports:
          - "2000-2004:2000-2004"
        volumes:
          - greyfish:/greyfish

        environment:
            - greyfish_key
            - greyfish_path
            - greyfish_threads
            - URL_BASE
            - REDIS_AUTH

        command: "tail -F anything"

    # Temporary keys and instance information
    redis:
        image: 'redis:4-alpine'
        container_name: redis
        environment:
            - REDIS_AUTH
        command: redis-server --requirepass $REDIS_AUTH
        ports:
            - '6379:6379'


volumes:
  greyfish:
    external: true
