version: '3'


services:


  easy_wetty:
    build: .
    image: "easy_wetty/standalone"
    container_name: wetty
    tty: true
    environment:
      - MANAGER_NODE

    ports:
      - "80:3000"
    command: "yarn start"
